version: '2'
services:
  api:
    build: 
      context: ..
      dockerfile: docker/api.dockerfile
  web:
    build:
      context: ..
      dockerfile: docker/web.dockerfile
      args:
        - NODE_OPTIONS=--openssl-legacy-provider
        - HOST=0.0.0.0
    environment: 
      - NODE_OPTIONS=--openssl-legacy-provider
      - HOST=0.0.0.0
  nginx:
    build: 
      context: ..
      dockerfile: docker/nginx.dockerfile
    ports:
     - "8000:80"